force-app/main/default/objects/Case/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Related_to_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_to_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Related_to_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PWChrono_ProjectController.cls
public inherited sharing class PWChrono_ProjectController {
  @AuraEnabled(cacheable=true)
  public static List<Case> getTasks(Id projectId) {
    return [
      SELECT Id, CaseNumber, Subject, Status, Priority, Due_Date__c
      FROM Case
      WHERE Related_to_Opportunity__c = :projectId
    ];
  }

  @AuraEnabled(cacheable=true)
  public static List<Task> getSubtasks(Id taskId) {
    return [
      SELECT Id, Subject, ActivityDate, Status
      FROM Task
      WHERE WhatId = :taskId
    ];
  }
}